[mgr]
prepend_keymap = [
  { on = ["g", "h"], run = "cd ~", desc = "Go to home" },
  { on = ["g", "c"], run = "cd ~/.config", desc = "Go to config" },
  { on = ["g", "d"], run = "cd ~/Downloads", desc = "Go to downloads" },
  { on = ["g", "p"], run = "cd ~/Projects", desc = "Go to projects" },
  { on = ["g", "."], run = "cd ~/.local/share/chezmoi", desc = "Go to dotfiles" },

  { on = "<C-h>", run = "hidden toggle", desc = "Toggle hidden files" },
  { on = "a", run = "create", desc = "Create file/directory" },
  { on = "e", run = "open --interactive", desc = "Open interactively" },
  { on = "E", run = 'shell --orphan -- code .', desc = "Open current directory in VS Code" },
  { on = "!", run = "shell --block --interactive", desc = "Run shell command" },
  { on = "<C-f>", run = "plugin fzf", desc = "Fuzzy find" },
  { on = "r", run = "rename --cursor=before_ext", desc = "Rename" },

  { on = ["y", "p"], run = "copy path", desc = "Copy file path" },
  { on = ["y", "d"], run = "copy dirname", desc = "Copy directory path" },
  { on = ["y", "n"], run = "copy filename", desc = "Copy filename" },

  { on = ["b", "z"], run = "plugin ouch --args=zip", desc = "Compress to zip" },
  { on = ["b", "t"], run = "plugin ouch --args=tar.gz", desc = "Compress to tar.gz" },
  { on = ["g", "i"], run = "plugin lazygit", desc = "run lazygit" }
]

[input]
prepend_keymap = [
  { on = "<C-a>", run = "move -999", desc = "Move to line start" },
  { on = "<C-e>", run = "move 999", desc = "Move to line end" },
  { on = "<C-k>", run = "kill eol", desc = "Kill to line end" },
]