import { createHash } from "node:crypto";
import { chmodSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { isAbsolute, join } from "node:path";
import { setTimeout as sleep } from "node:timers/promises";

const SOURCE = "powerfooI/roamgate";
const PLUGIN = "roamgate";
const MARKER = "Generated by roamgate service install.";
const SHELL = 'set -a; if [ -f "$1" ]; then . "$1"; fi; set +a; exec "$2"';

// Decode the literal subset shared by POSIX shell and systemd EnvironmentFile.
// Never source the file: reject expansion/operators rather than executing them.
export function parseEnv(contents) {
    const env = {};
    for (const line of contents.split("\n")) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
        if (!match) throw new Error("Roamgate env is not a literal assignment; apply its private template");
        const raw = match[2].trim();
        let value = "";
        if (raw.startsWith('"') && raw.endsWith('"') && raw.length >= 2) {
            const body = raw.slice(1, -1);
            for (let i = 0; i < body.length; i++) {
                if (body[i] === "\\" && i === body.length - 1) throw new Error("Roamgate env has an unterminated quoted value; apply its private template");
                if (body[i] === "\\" && /[\\"$`]/.test(body[i + 1] ?? "")) value += body[++i];
                else if (/["$`]/.test(body[i])) throw new Error("Roamgate env contains shell expansion; apply its updated private template");
                else value += body[i];
            }
        } else if (raw.startsWith("'") && raw.endsWith("'") && !raw.slice(1, -1).includes("'")) {
            value = raw.slice(1, -1);
        } else if (/^[A-Za-z0-9_.:/\[\]-]*$/.test(raw)) value = raw;
        else throw new Error("Roamgate env contains unsupported quoting; apply its private template");
        if (/[\x00-\x1f\x7f]/.test(value)) throw new Error("Roamgate env values must be single-line and contain no control characters");
        env[match[1]] = value;
    }
    return env;
}

export function loadConfig(file) {
    if (!existsSync(file)) throw new Error("Roamgate env is missing; apply its private template first");
    if ((statSync(file).mode & 0o077) !== 0) throw new Error("Roamgate env must be private (0600)");
    const contents = readFileSync(file, "utf8");
    const env = parseEnv(contents);
    if (!env.HOST || !env.ROAMGATE_PASSWORD) throw new Error("Roamgate automatic synchronization requires HOST and a fixed ROAMGATE_PASSWORD");
    if (!/^[0-9]+$/.test(env.PORT ?? "") || Number(env.PORT) < 1 || Number(env.PORT) > 65535) {
        throw new Error("Roamgate PORT must be an integer between 1 and 65535");
    }
    if (!/^[A-Za-z0-9_.:\[\]-]+$/.test(env.HOST)) throw new Error("Roamgate HOST must be a literal hostname/address");
    if (env.ROAMGATE_TLS_CERT || env.ROAMGATE_TLS_KEY) {
        throw new Error("Roamgate custom HTTPS configuration is not managed by this HTTP service synchronizer");
    }
    const host = env.HOST === "0.0.0.0" ? "127.0.0.1" : env.HOST === "::" ? "[::1]" : env.HOST;
    let origin;
    try { origin = new URL(`http://${host.includes(":") && !host.startsWith("[") ? `[${host}]` : host}:${env.PORT}`).origin; }
    catch { throw new Error("Roamgate HOST is not a valid hostname/address"); }
    return { contents, env, origin };
}

export function runNative(args, { allowAbsent = false, timeoutMs = 10_000,
    spawn = (argv, options) => Bun.spawnSync(argv, options),
} = {}) {
    const result = spawn(args, { stdout: "pipe", stderr: "pipe", timeout: timeoutMs });
    if (result.exitCode !== 0) {
        if (allowAbsent && args[0] === "launchctl" && args[1] === "print" && result.exitCode === 113 &&
            result.stderr.toString().includes("Could not find service")) return "";
        const exit = Number.isInteger(result.exitCode) ? result.exitCode : "unknown";
        throw new Error(`Roamgate native ${args[0]} ${args[1]} failed (exit ${exit}); refusing to refresh its service`);
    }
    const output = result.stdout.toString();
    if (args[0] === "launchctl" && args[1] === "print" && !output.trim()) {
        throw new Error("launchctl print returned an empty service state; refusing to refresh Roamgate");
    }
    return output;
}

function runHerdr(args) {
    const result = Bun.spawnSync(["herdr", ...args], { stdout: "pipe", stderr: "pipe", timeout: 10_000 });
    if (result.exitCode !== 0) throw new Error(`herdr ${args.slice(0, 3).join(" ")} failed; inspect the plugin logs`);
    return result.stdout.toString();
}

function json(raw, description) {
    try { return JSON.parse(raw); }
    catch { throw new Error(`Invalid ${description} response; no private response content was printed`); }
}

function systemdPath(path) {
    return Array.from(path, character => {
        if (/^[A-Za-z0-9/_.:@+-]$/.test(character)) return character;
        if (character === "%") return "%%";
        return Array.from(Buffer.from(character), byte => `\\x${byte.toString(16).padStart(2, "0")}`).join("");
    }).join("");
}

function optionalStat(path) {
    try { return lstatSync(path); }
    catch (error) {
        if (error.code === "ENOENT") return null;
        throw new Error("Unable to inspect Roamgate service files; refusing to replace its service");
    }
}

export function assertGeneratedService(binaryPath, previousBinary, {
    home = homedir(), platform = process.platform, native = runNative, requireLaunchdAbsent = false,
} = {}) {
    const config = join(home, ".config", "roamgate", "roamgate.env");
    const binaries = [...new Set([binaryPath, previousBinary].filter(value => typeof value === "string" && value))];
    let definition, loadedLaunchd = false;
    if (platform === "darwin") {
        definition = join(home, "Library", "LaunchAgents", "dev.roamgate.plist");
        if (optionalStat(join(home, "Library", "LaunchAgents", "dev.herdr.herdr-gui.plist"))) {
            throw new Error("A legacy Herdr GUI service definition exists; refusing an automatic forced migration");
        }
        const loaded = native(["launchctl", "print", `gui/${process.getuid()}/dev.roamgate`], { allowAbsent: true });
        loadedLaunchd = Boolean(loaded);
        const loadedPath = loaded.match(/^\s*path = (.+)$/m)?.[1];
        if (loaded && loadedPath !== definition) throw new Error("Roamgate is loaded from a custom launchd definition; refusing to replace it");
        if (loaded && requireLaunchdAbsent) throw new Error("Roamgate launchd job reappeared before start; refusing to reload it");
    } else if (platform === "linux") {
        definition = join(home, ".config", "systemd", "user", "roamgate.service");
        if (optionalStat(join(home, ".config", "systemd", "user", "herdr-gui.service"))) {
            throw new Error("A legacy Herdr GUI service definition exists; refusing an automatic forced migration");
        }
        const properties = native(["systemctl", "--user", "show", "roamgate.service", "--property=FragmentPath", "--property=DropInPaths"]);
        const fragment = properties.match(/^FragmentPath=(.*)$/m)?.[1];
        const dropIns = properties.match(/^DropInPaths=(.*)$/m)?.[1];
        if (fragment === undefined || dropIns === undefined) throw new Error("Unable to inspect Roamgate systemd overrides");
        if (dropIns || (fragment && fragment !== definition)) throw new Error("Roamgate has custom systemd overrides; refusing to replace its service");
        // The manager's cached properties omit files added since its last
        // daemon-reload. Inspect its full on-disk lookup path before start's reload.
        const paths = json(native(["busctl", "--user", "--json=short", "get-property", "org.freedesktop.systemd1",
            "/org/freedesktop/systemd1", "org.freedesktop.systemd1.Manager", "UnitPath"]), "systemd unit lookup");
        // Read the actual manager's paths, not paths derived from this client's
        // potentially different XDG environment. JSON preserves spaces in paths.
        const lookup = paths.type === "as" && Array.isArray(paths.data) ? paths.data : [];
        if (!lookup.length || lookup.some(path => typeof path !== "string" || !isAbsolute(path)) || !lookup.includes(join(definition, ".."))) {
            throw new Error("Unable to inspect Roamgate systemd unit lookup paths");
        }
        const effective = lookup.map(path => join(path, "roamgate.service")).find(path => optionalStat(path));
        if (effective && effective !== definition) throw new Error("Roamgate has a pending custom systemd definition; refusing to replace its service");
        for (const directory of lookup) {
            for (const name of ["roamgate.service.d", "service.d"]) {
                const path = join(directory, name);
                const entry = optionalStat(path);
                if (entry && (!entry.isDirectory() || readdirSync(path).some(file => file.endsWith(".conf")))) {
                    throw new Error("Roamgate has on-disk systemd overrides; refusing to activate them implicitly");
                }
            }
        }
    } else throw new Error("Roamgate service synchronization supports macOS and Linux only");

    const entry = optionalStat(definition);
    if (!entry) {
        if (loadedLaunchd) throw new Error("Cannot verify the loaded Roamgate service without its definition; refusing to remove it");
        return;
    }
    if (entry.isSymbolicLink()) throw new Error("Roamgate service definition is a custom symlink; refusing to replace it");
    if (!entry.isFile()) throw new Error("Roamgate service definition is not a regular file; refusing to replace it");
    const contents = readFileSync(definition, "utf8");
    if (!contents.includes(MARKER)) throw new Error("Roamgate service definition is not officially generated; refusing to overwrite it");
    let canonical;
    if (platform === "darwin") {
        const actual = json(native(["plutil", "-convert", "json", "-o", "-", definition]), "launchd definition");
        canonical = binaries.some(binary => {
            const expected = {
                Label: "dev.roamgate", ProgramArguments: ["/bin/sh", "-c", SHELL, "roamgate-service", config, binary],
                RunAtLoad: true, KeepAlive: true, ThrottleInterval: 2, ProcessType: "Background",
                StandardOutPath: join(home, "Library", "Logs", "roamgate.stdout.log"),
                StandardErrorPath: join(home, "Library", "Logs", "roamgate.stderr.log"),
            };
            return Object.keys(actual).length === Object.keys(expected).length && Object.entries(expected).every(([key, value]) =>
                JSON.stringify(actual[key]) === JSON.stringify(value));
        });
    } else {
        canonical = binaries.some(binary => contents.replaceAll("\r\n", "\n").trim() === `# ${MARKER}
[Unit]
Description=Roamgate
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
EnvironmentFile=-${systemdPath(config)}
ExecStart=${systemdPath(binary)}
Restart=always
RestartSec=2
TimeoutStopSec=15

[Install]
WantedBy=default.target`);
    }
    if (!canonical) throw new Error("Roamgate generated service was customized or points to an unverified binary; refusing to overwrite it");
}

async function unloadLaunchdService({ home, native, wait, stopTimeoutMs, now }) {
    const target = `gui/${process.getuid()}/dev.roamgate`;
    const deadline = now() + stopTimeoutMs;
    const remaining = () => {
        const ms = deadline - now();
        if (ms <= 0) throw new Error("Timed out waiting for Roamgate launchd removal; refusing to start it or update its service stamp");
        return ms;
    };
    const control = (operation, options = {}) => {
        const output = native(["launchctl", operation, target], {
            ...options, timeoutMs: Math.min(10_000, Math.ceil(remaining())),
        });
        remaining(); // An absent reply received after expiry is not success.
        return output;
    };
    const probe = () => control("print", { allowAbsent: true });
    const loaded = probe();
    if (!loaded) return;
    if (loaded.match(/^\s*path = (.+)$/m)?.[1] !== join(home, "Library", "LaunchAgents", "dev.roamgate.plist")) {
        throw new Error("Roamgate launchd definition changed before removal; refusing to stop a custom service");
    }
    // Official install --force calls bootout then bootstrap without waiting.
    // bootout acknowledges the request, not completed job removal (launchd 37).
    control("bootout");
    while (probe()) await wait(Math.min(100, remaining()));
}

export async function waitForAction({ run = runHerdr, wait = sleep, actionTimeoutMs = 60_000 } = {}) {
    const invoked = json(run(["plugin", "action", "invoke", "start", "--plugin", PLUGIN]), "Herdr action");
    const logId = invoked.result?.log?.log_id;
    if (typeof logId !== "string") throw new Error("Roamgate start did not return a command log ID");
    const deadline = Date.now() + actionTimeoutMs;
    while (Date.now() < deadline) {
        const response = json(run(["plugin", "log", "list", "--plugin", PLUGIN, "--limit", "100"]), "Herdr log");
        if (!Array.isArray(response.result?.logs)) throw new Error("Unexpected Herdr plugin log response");
        const log = response.result.logs.find(entry => entry.log_id === logId);
        if (log && log.status !== "running" && log.status !== "queued") {
            if (log.plugin_id === PLUGIN && log.action_id === "start" && log.status === "succeeded" && log.exit_code === 0) return;
            const exit = Number.isInteger(log.exit_code) ? log.exit_code : "unknown";
            throw new Error(`Roamgate start failed (exit ${exit}); inspect herdr plugin log list --plugin roamgate`);
        }
        await wait(250);
    }
    throw new Error("Timed out waiting for Roamgate start; the service stamp was not updated");
}

export async function reconcile(ref, {
    home = homedir(), stateHome = process.env.XDG_STATE_HOME || join(home, ".local", "state"),
    platform = process.platform, run = runHerdr, native = runNative, request = fetch, wait = sleep,
    actionTimeoutMs = 60_000, healthTimeoutMs = 20_000, stopTimeoutMs = 20_000, stopNow = () => performance.now(),
} = {}) {
    const stateDir = join(stateHome, "chezmoi");
    const ownershipFile = join(stateDir, "herdr-plugins");
    const ownership = existsSync(ownershipFile) ? readFileSync(ownershipFile, "utf8").split("\n") : [];
    if (!ownership.includes(`${SOURCE}\t${ref}`)) {
        console.log("    Roamgate is not owned at the requested ref by dotfiles; skipping service reconciliation");
        return "skipped";
    }
    if (!/^v[0-9]+\.[0-9]+\.[0-9]+$/.test(ref)) throw new Error("Roamgate service synchronization requires a stable vX.Y.Z ref");
    const response = json(run(["plugin", "list", "--json", "--plugin", PLUGIN]), "Herdr plugin");
    const plugin = response.result?.plugins?.find(entry => entry.plugin_id === PLUGIN);
    if (!plugin || plugin.source?.kind !== "github" || plugin.source.owner !== "powerfooI" || plugin.source.repo !== "roamgate" ||
        plugin.source.requested_ref !== ref || plugin.version !== ref.slice(1) || typeof plugin.plugin_root !== "string" || !isAbsolute(plugin.plugin_root)) {
        throw new Error("Roamgate plugin is not at the requested ref/source; run the [10] plugin synchronization first");
    }
    if (plugin.enabled !== true) {
        console.log("    Roamgate plugin is disabled; leaving its service alone");
        return "skipped";
    }
    const config = loadConfig(join(home, ".config", "roamgate", "roamgate.env"));
    const binaryPath = join(plugin.plugin_root, "server", "roamgate");
    const stampFile = join(stateDir, "roamgate");
    let previous = null;
    try { previous = JSON.parse(readFileSync(stampFile, "utf8")); }
    catch { /* An absent/corrupt stamp is never proof that the daemon is current. */ }
    const stamp = { ref, configHash: createHash("sha256").update(config.contents).digest("hex"), binaryPath };

    async function verified() {
        // Passwords stay in request bodies, never argv, URLs, stamps or diagnostics.
        const options = { redirect: "manual", signal: AbortSignal.timeout(1500) };
        try {
            const anonymous = await request(`${config.origin}/api/health`, options);
            if (anonymous.status !== 401) return false;
            const login = await request(`${config.origin}/api/login`, { ...options, signal: AbortSignal.timeout(1500),
                method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: config.env.ROAMGATE_PASSWORD }) });
            if (!login.ok) return false;
            const cookie = login.headers.get("set-cookie")?.match(/(?:^|,\s*)herdr_auth=([^;\s,]+)/)?.[1];
            if (!cookie) return false;
            const health = await request(`${config.origin}/api/health`, { ...options, signal: AbortSignal.timeout(1500), headers: { cookie: `herdr_auth=${cookie}` } });
            if (!health.ok) return false;
            const body = await health.json();
            return body.ok === true && body.version === ref.slice(1) && body.auth_required === true;
        } catch { return false; }
    }

    if (JSON.stringify(previous) === JSON.stringify(stamp) && await verified()) {
        console.log("    Roamgate service already synchronized at the requested running version");
        return "synchronized";
    }
    assertGeneratedService(binaryPath, previous?.binaryPath, { home, platform, native });
    if (platform === "darwin") {
        await unloadLaunchdService({ home, native, wait, stopTimeoutMs, now: stopNow });
        // Recheck both cold and warm paths: another process could edit the file
        // or register a job while we wait. Do not stop/reload a reappeared job.
        assertGeneratedService(binaryPath, previous?.binaryPath, { home, platform, native, requireLaunchdAbsent: true });
    }
    console.log("    Refreshing the generated Roamgate service and restarting it");
    // Official start = service install --force. restart alone does not update
    // a stale executable path in the native service definition.
    await waitForAction({ run, wait, actionTimeoutMs });
    const deadline = Date.now() + healthTimeoutMs;
    while (!await verified()) {
        if (Date.now() >= deadline) throw new Error("Roamgate running version/password verification failed; the service stamp was not updated");
        await wait(250);
    }
    mkdirSync(stateDir, { recursive: true, mode: 0o700 });
    const temporary = `${stampFile}.tmp-${process.pid}`;
    try {
        writeFileSync(temporary, `${JSON.stringify(stamp)}\n`, { mode: 0o600 });
        chmodSync(temporary, 0o600);
        renameSync(temporary, stampFile);
    } finally { rmSync(temporary, { force: true }); }
    console.log("    Roamgate service synchronized; running version verified without printing credentials");
    return "synchronized";
}

if (import.meta.main) {
    try { await reconcile(process.argv[2]); }
    catch (error) {
        console.error(`    Error: ${error.message}`);
        process.exitCode = 1;
    }
}
